## spring 2.4 이후에는 group

spring:
  profiles:
    group:
      "dev": "localdb, common"

---
spring:
  profiles:
    group:
      "test": "h2db, common"

---

spring:
  profiles:
    group:
      "prod": "ec2db, common"

---

spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    database: mysql
    hibernate:
      #  dialect : org.hibernate.dialect.MySQL57Dialect // spring boot make dialect automatically?
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging.level:
  com.B305: DEBUG
  org.hibernate.SQL: debug
# org.hibernate.type: trace

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: always
      encoding: utf-8
---

spring:
  config:
    activate:
      on-profile: "h2db"
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
---

spring:
  config:
    activate:
      on-profile: "ec2db"
  datasource:
    url: jdbc://mysql-575bb7b667-wpk29:3307/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
---